apiVersion: apps/v1
kind: Deployment
metadata:
  name: connor-bunch-blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: connor-bunch-blog
  template:
    metadata:
      labels:
        app: connor-bunch-blog
    spec:
      containers:
      - name: connor-bunch-blog
        image: registry.corp.ridetracker.io/universal-blog:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: connor-bunch-blog
spec:
  selector:
    app: connor-bunch-blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 31123
  type: NodePort